# Generated by Django 2.2.5 on 2019-11-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='products.CarType'),
        ),
        migrations.AlterField(
            model_name='car',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='products.FuelType'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='car_photos'),
        ),
    ]
